# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "capybara", "3.39.0"
gem "rspec", "3.12.0"
gem "selenium-webdriver", "4.8.6"
gem "ffi", "1.15.5"
gem "cucumber", "8.0.0"
gem "site_prism", "3.7.3"